//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contenedor_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups_mod
    {
        public int ID { get; set; }
        public int Id_mod { get; set; }
        public int Id_group { get; set; }
    
        public virtual group group { get; set; }
        public virtual modules_app modules_app { get; set; }
    }
}
