//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contenedor_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rols_app
    {
        public int id_rol { get; set; }
        public int Id_mod { get; set; }
        public string name_role { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual modules_app modules_app { get; set; }
    }
}
